org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# Add the following to fix resource linking issues
android.enableR8.fullMode=false
android.nonTransitiveRClass=false
android.nonFinalResIds=false

android.useAndroidX=true
kotlin.code.style=official
